### ISSUE TITLE
sqlite3.InterfaceError 

### ISSUE THREAD

**Issue by k-f-** [geigerzaehler/beets-check#14]
beets-check explodes sometimes when using it in conjunction with beets embedart.

I will provide these files if you like.

issue over at /beets: https://github.com/sampsyo/beets/issues/1242

```
kef@kathmandu in 2014Music/
› beet -v embedart -f ../Music/Nobuo\ Uematsu/1993\ -\ Piano\ Collections_\ Final\ Fantasy\ V/cover.jpg path:../Music/Nobuo\ Uematsu/1993\ -\ Piano\ Collections_\ Final\ Fantasy\ V
user configuration: /Users/kef/.beets/config.yaml
data directory: /Users/kef/.beets
Sending event: pluginload
artresizer: method is (2, (6, 9, 0))
library database: /Volumes/r0ckc4ndy/Music/.beetslibrary.blb
library directory: /Volumes/r0ckc4ndy/Music
Sending event: library_opened
No album art present in Nobuo Uematsu - A Presentiment.
Resizing album art to 500 pixels wide
artresizer: ImageMagick resizing /Volumes/r0ckc4ndy/Music/Nobuo Uematsu/1993 - Piano Collections_ Final Fantasy V/cover.jpg to /var/folders/dv/l3_5wprd61q5q8csk3y6hbx00000gn/T/tmpFLk4C1.jpg
embedart: embedding /var/folders/dv/l3_5wprd61q5q8csk3y6hbx00000gn/T/tmpFLk4C1.jpg
Sending event: write
Sending event: after_write
Traceback (most recent call last):
  File "/usr/local/bin/beet", line 9, in <module>
    load_entry_point('beets==1.3.10', 'console_scripts', 'beet')()
  File "/usr/local/lib/python2.7/site-packages/beets/ui/__init__.py", line 945, in main
    _raw_main(args)
  File "/usr/local/lib/python2.7/site-packages/beets/ui/__init__.py", line 935, in _raw_main
    subcommand.func(lib, suboptions, subargs)
  File "/usr/local/lib/python2.7/site-packages/beetsplug/embedart.py", line 74, in embed_func
    compare_threshold, ifempty)
  File "/usr/local/lib/python2.7/site-packages/beetsplug/embedart.py", line 141, in embed_item
    item.try_write(itempath)
  File "/usr/local/lib/python2.7/site-packages/beets/library.py", line 509, in try_write
    self.write(path)
  File "/usr/local/lib/python2.7/site-packages/beets/library.py", line 500, in write
    plugins.send('after_write', item=self, path=path)
  File "/usr/local/lib/python2.7/site-packages/beets/plugins.py", line 406, in send
    handler(**args)
  File "/usr/local/lib/python2.7/site-packages/beetsplug/check.py", line 126, in item_after_write
    set_checksum(item)
  File "/usr/local/lib/python2.7/site-packages/beetsplug/check.py", line 35, in set_checksum
    item.store()
  File "/usr/local/lib/python2.7/site-packages/beets/library.py", line 238, in store
    super(LibModel, self).store()
  File "/usr/local/lib/python2.7/site-packages/beets/dbcore/db.py", line 364, in store
    (self.id, key, value),
  File "/usr/local/lib/python2.7/site-packages/beets/dbcore/db.py", line 655, in mutate
    cursor = self.db._connection().execute(statement, subvals)
sqlite3.InterfaceError: Error binding parameter 2 - probably unsupported type.
```

**Comment by geigerzaehler** [comment]
I opened a pull request with a proposed fix. Can you confirm that it works for you?
```
pip install git+https://github.com/sampsyo/beets.git#write-tags
```

**Comment by geigerzaehler** [comment]
Timed out.
