### ISSUE TITLE
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2

### ISSUE THREAD

**Issue by pwenzel** [geigerzaehler/beets-check#16]
I tried running `beet check -a` on my library and ran into the error `UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 82: ordinal not in range(128)`.  

I'm not sure what file caused this error, but would be happy to help if I know how to render more useful debug logs. 

Here is my terminal output:

```
beet check -a 
Looking for files without checksums...
Traceback (most recent call last):      
  File "/usr/local/bin/beet", line 9, in <module>
    load_entry_point('beets==1.3.10', 'console_scripts', 'beet')()
  File "/Library/Python/2.7/site-packages/beets/ui/__init__.py", line 945, in main
    _raw_main(args)
  File "/Library/Python/2.7/site-packages/beets/ui/__init__.py", line 935, in _raw_main
    subcommand.func(lib, suboptions, subargs)
  File "/Library/Python/2.7/site-packages/beetsplug/check.py", line 226, in func
    self.add()
  File "/Library/Python/2.7/site-packages/beetsplug/check.py", line 254, in add
    self.execute_with_progress(add, items, msg='Adding missing checksums')
  File "/Library/Python/2.7/site-packages/beetsplug/check.py", line 416, in execute_with_progress
    for _ in e.map(func, args):
  File "/Library/Python/2.7/site-packages/concurrent/futures/_base.py", line 580, in map
    yield future.result()
  File "/Library/Python/2.7/site-packages/concurrent/futures/_base.py", line 400, in result
    return self.__get_result()
  File "/Library/Python/2.7/site-packages/concurrent/futures/_base.py", line 359, in __get_result
    reraise(self._exception, self._traceback)
  File "/Library/Python/2.7/site-packages/concurrent/futures/_compat.py", line 107, in reraise
    exec('raise exc_type, exc_value, traceback', {}, locals_)
  File "/Library/Python/2.7/site-packages/concurrent/futures/thread.py", line 61, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Library/Python/2.7/site-packages/beetsplug/check.py", line 244, in add
    log.debug(u'adding checksum for {0}'.format(item.path))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 82: ordinal not in range(128)
```

This is using the most recent version of `beet check` from master, at revision `62edbb5630`.

**Comment by geigerzaehler** [comment]
Should be solved by #17 . Feel free to reopen if it’s not the case.
