### ISSUE TITLE
Problem checking flac files

### ISSUE THREAD

**Issue by MadPierrot** [geigerzaehler/beets-check#20]
Hi all!

 opened this issue to report a problem when beets imports an album in FLAC format, I can just see a flac process spawned, then beets dies leaving a trace, cannot understand why.

This is a complete output of error, tell me if a strace could help:

$ beet -v import /mnt/***/Method\ Man*
user configuration: /home/my_user/.config/beets/config.yaml
data directory: /home/my_user/.config/beets
plugin paths: 
Sending event: pluginload
library database: /home/my_user/.config/beets/library.db
library directory: /mnt/syno-music/aaa
Sending event: library_opened
Sending event: import_begin
state file could not be read: [Errno 2] No such file or directory: u'/home/my_user/.config/beets/state.pickle'
Sending event: import_task_created
Sending event: import_task_start
Looking up: /mnt/***/Method Man/1994 - Tical
Tagging Method Man - Tical
Searching for discovered album ID: 48feb668-a0fc-382a-9cde-1cb1f55f31b1
Sending event: import_task_created
Sending event: import_task_created
Candidate: Method Man - Tical
Success. Distance: 0.00
Album ID match recommendation is Recommendation.strong
ID match.
Sending event: import_task_start
/mnt/***/Method Man/1994 - Tical (14 items)
Looking up: /mnt/***/Method Man/1995 - I'll Be There for You_You're All I Need to Get By
Tagging:
    Method Man - Tical
Tagging Method Man - I'll Be There for You/You're All I Need to Get By
URL:
    http://musicbrainz.org/release/48feb668-a0fc-382a-9cde-1cb1f55f31b1
Searching for discovered album ID: 8ad0facc-4cd2-4d3d-b8d0-0d5819b59442
(Similarity: 100.0%) (CD, 1995, XE, Def Jam Recordings)
Sending event: import_task_choice
Sending event: import_task_created
Sending event: import_task_created
Sending event: import_task_created
state file could not be read: [Errno 2] No such file or directory: u'/home/my_user/.config/beets/state.pickle'
Sending event: import_task_created
state file could not be read: [Errno 2] No such file or directory: u'/home/my_user/.config/beets/state.pickle'
Candidate: Method Man - I'll Be There for You/You're All I Need to Get By
Success. Distance: 0.00
Album ID match recommendation is Recommendation.strong
ID match.
Sending event: import_task_start
Looking up: /mnt/***/Method Man/1995 - The Riddler
Tagging Method Man - The Riddler
Searching for discovered album ID: 90fae1c0-f575-47a0-b36a-f3f15f37b86c
Sending event: import_task_created
Sending event: import_task_created
Sending event: import_task_created
Candidate: Method Man - The Riddler
Success. Distance: 0.04
Album ID match recommendation is Recommendation.medium
Search terms: Method Man - The Riddler
Album might be VA: False
/mnt/***/Method Man/1995 - I'll Be There for You_You're All I Need to Get By (4 items)
Tagging:
    Method Man - I'll Be There for You/You're All I Need to Get By
URL:
    http://musicbrainz.org/release/8ad0facc-4cd2-4d3d-b8d0-0d5819b59442
(Similarity: 100.0%) (tracks) (CD, 1995, GB, Def Jam Recordings)
Sending event: import_task_apply
 * Release Yo' Delf (Prodigy mix) (5:55) -> Release Yo' Delf (Prodigy mix) (5:45) (length)
Sending event: import_task_choice
0 of 14 items replaced
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Sending event: database_change
Evaluating 5 candidates.
Candidate: Method Man - The Riddler
Duplicate.
Candidate: Method Man - The Riddler: Remix by The RZA
Success. Distance: 0.49
Candidate: Method Man - Say
Success. Distance: 0.68
Candidate: Method Man - I'll Be There for You/You're All I Need to Get By
Success. Distance: 0.64
Candidate: Method Man - I'll Be There for You/You're All I Need to Get By
Success. Distance: 0.64
Traceback (most recent call last):
  File "/usr/local/bin/beet", line 9, in <module>
    load_entry_point('beets==1.3.13', 'console_scripts', 'beet')()
  File "/usr/local/lib/python2.7/dist-packages/beets/ui/__init__.py", line 1104, in main
    _raw_main(args)
  File "/usr/local/lib/python2.7/dist-packages/beets/ui/__init__.py", line 1094, in _raw_main
    subcommand.func(lib, suboptions, subargs)
  File "/usr/local/lib/python2.7/dist-packages/beets/ui/commands.py", line 893, in import_func
    import_files(lib, paths, query)
  File "/usr/local/lib/python2.7/dist-packages/beets/ui/commands.py", line 870, in import_files
    session.run()
  File "/usr/local/lib/python2.7/dist-packages/beets/importer.py", line 316, in run
    pl.run_parallel(QUEUE_SIZE)
  File "/usr/local/lib/python2.7/dist-packages/beets/util/pipeline.py", line 301, in run
    out = self.coro.send(msg)
  File "/usr/local/lib/python2.7/dist-packages/beets/util/pipeline.py", line 183, in coro
    func(*(args + (task,)))
  File "/usr/local/lib/python2.7/dist-packages/beets/importer.py", line 1343, in plugin_stage
    func(session, task)
  File "/usr/local/lib/python2.7/dist-packages/beets/plugins.py", line 117, in wrapper
    assert self._log.level == logging.NOTSET
AssertionError

# pip list
Warning: cannot find svn location for apsw==3.8.6-r1
apsw (3.8.6-r1)
apt-xapian-index (0.47)
argparse (1.2.1)
BeautifulSoup (3.2.1)
beets (1.3.13)
beets-check (0.10.0-beta.0)
cffi (0.8.6)
characteristic (0.1.0)
chardet (2.3.0)
CherryPy (3.5.0)
colorama (0.3.2)
cryptography (0.6.1)
cssselect (0.9.1)
cssutils (0.9.10)
defusedxml (0.4.1)
dnspython (1.12.0)
docutils (0.12)
enum34 (1.0.4)
feedparser (5.1.3)
futures (3.0.2)
gyp (0.1)
html5lib (0.999)
jellyfish (0.5.0)
lxml (3.4.0)
Markdown (2.5.1)
mechanize (0.2.5)
munkres (1.0.7)
musicbrainzngs (0.5)
mutagen (1.29)
nbxmpp (0.5.1)
ndg-httpsclient (0.3.2)
netifaces (0.10.4)
numpy (1.8.2)
PAM (0.4.2)
Parsley (1.2)
Pillow (2.6.1)
pip (1.5.6)
ply (3.4)
psutil (2.1.1)
pyasn1 (0.1.7)
pyasn1-modules (0.0.5)
pycparser (2.10)
pycrypto (2.6.1)
pycurl (7.19.5)
Pygments (2.0.1)
pygobject (3.14.0)
pyliblzma (0.5.3)
pyOpenSSL (0.14)
pyparsing (2.0.3)
pyserial (2.6)
python-apt (0.9.3.11)
python-dateutil (2.2)
python-debian (0.1.27)
python-debianbts (1.11)
pyxdg (0.25)
PyYAML (3.11)
reportbug (6.6.3)
repoze.lru (0.6)
requests (2.4.3)
roman (2.0.0)
Routes (2.0)
service-identity (1.0.0)
setuptools (5.5.1)
six (1.8.0)
SOAPpy (0.12.22)
torbrowser-launcher (0.1.9)
Twisted (14.0.2)
Twisted-Conch (14.0.2)
Twisted-Core (14.0.2)
Twisted-Lore (14.0.2)
Twisted-Mail (14.0.2)
Twisted-Names (14.0.2)
Twisted-News (14.0.2)
Twisted-Runner (14.0.2)
Twisted-Web (14.0.2)
Twisted-Words (14.0.2)
txsocksx (0.0.0)
Unidecode (0.04.17)
urllib3 (1.9.1)
uTidylib (0.2)
vboxapi (1.0)
WebOb (1.4)
wheel (0.24.0)
wsgiref (0.1.2)
wstools (0.4.3)
zope.interface (4.1.1)

**Comment by geigerzaehler** [comment]
Hi @MadPierrot. Thanks for reporting this but I cannot find anything related to the *check* plugin. Does importing work if you disable the plugin?

**Comment by MadPierrot** [comment]
Hello,

   I disabled only your plugin, and other confs works well, didn't find any
useful information in previous pasted output, so I filled this issue.

As I wrote in my last post, I saw a flac instance an instant before beets
crash, so (maybe) I can assume that all works well until flac starts the
verify.

Don't know much of python, but I can provide any needed information.


Hope you can help me.

Regards.





Il sabato 30 maggio 2015, Thomas Scholtes <notifications@github.com> ha
scritto:
> Hi @MadPierrot. Thanks for reporting this but I cannot find anything
related to the check plugin. Does importing work if you disable the plugin?
>
> —
> Reply to this email directly or view it on GitHub.<
https://ci6.googleusercontent.com/proxy/VP8dyB7__nr_CLJpEKb3hkxyM0e2OUpLtkqhm0aUnQEfgAjGUoC0AZo463Bs-62640YKv4Is9C-EZ9-Nwi6cSOCq9vRU-0q3YO9KwOTGOY23Yh65X_0aFXD74tho9WO5w42W0vD6XjMCWkSgnWvuAYOjnH_BjQ=s0-d-e1-ft#https://github.com/notifications/beacon/AIBxgeRAcatYoI2SOJ-VoPzrVSk8npZGks5oOYnQgaJpZM4EsbCH.gif>

**Comment by MadPierrot** [comment]
up?

if you need more specific infos please ask :)
