### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by somasis** [geigerzaehler/beets-check#28]
Aside from it seeing no commits since 2015, some API changes (or perhaps just Python 3) seem to have done this plugin in pretty badly; importing anything with this plugin enabled with the default settings gives this error:

```
Traceback (most recent call last):
  File "/usr/bin/beet", line 11, in <module>
    load_entry_point('beets==1.4.7', 'console_scripts', 'beet')()
  File "/usr/lib/python3.6/site-packages/beets/ui/__init__.py", line 1256, in main
    _raw_main(args)
  File "/usr/lib/python3.6/site-packages/beets/ui/__init__.py", line 1243, in _raw_main
    subcommand.func(lib, suboptions, subargs)
  File "/usr/lib/python3.6/site-packages/beets/ui/commands.py", line 937, in import_func
    import_files(lib, paths, query)
  File "/usr/lib/python3.6/site-packages/beets/ui/commands.py", line 914, in import_files
    session.run()
  File "/usr/lib/python3.6/site-packages/beets/importer.py", line 329, in run
    pl.run_sequential()
  File "/usr/lib/python3.6/site-packages/beets/util/pipeline.py", line 389, in run_sequential
    list(self.pull())
  File "/usr/lib/python3.6/site-packages/beets/util/pipeline.py", line 466, in pull
    out = coro.send(msg)
  File "/usr/lib/python3.6/site-packages/beets/util/pipeline.py", line 171, in coro
    task = func(*(args + (task,)))
  File "/usr/lib/python3.6/site-packages/beets/importer.py", line 1371, in user_query
    plugins.send('import_task_choice', session=session, task=task)
  File "/usr/lib/python3.6/site-packages/beets/plugins.py", line 452, in send
    result = handler(**arguments)
  File "/usr/lib/python3.6/site-packages/beets/plugins.py", line 124, in wrapper
    return func(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/beetsplug/check.py", line 152, in verify_import_integrity
    verify_integrity(item)
  File "/usr/lib/python3.6/site-packages/beetsplug/check.py", line 53, in verify_integrity
    checker.check(item)
  File "/usr/lib/python3.6/site-packages/beetsplug/check.py", line 486, in check
    process = Popen(self.cmdline.format(self.shellquote(syspath(item.path))),
  File "/usr/lib/python3.6/site-packages/beetsplug/check.py", line 507, in shellquote
    return "'" + s.replace("'", r"'\''") + "'"
TypeError: a bytes-like object is required, not 'str'
```

**Comment by geigerzaehler** [comment]
The error was due to the lack of python 3 support. I fixed that in #32. Please check out the new version and see if it works.
